import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = localFont({
  src: './assent/IranSansX/IranSansX/Webfonts/fonts/woff/IRANSansX-Light.woff'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={font.className}>{children}</body>
    </html>
  );
}
